name: Laravel

on:
  push:
    branches: [ "main", "Task1" ]
  pull_request:
    branches: [ "main", "Task1" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        
    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Run Tests
      run: php artisan test --env=testing
